CREATE TABLE Users(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(64),
  password CHAR(42),
  username VARCHAR(32),
  PRIMARY KEY(id)
);
