CREATE TABLE Users(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(64),
  password CHAR(42),
  username VARCHAR(32),
  PRIMARY KEY(id)
);

CREATE TABLE Projects(
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id SMALLINT UNSIGNED NOT NULL REFERENCES Users(id),
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(64),
  PRIMARY KEY(id)
);
